### ISSUE TITLE
Make a list of NPM dependencies

### ISSUE THREAD

**Issue by SomethingGeneric** [SomethingGeneric/oldwebsite#23]

**Comment by therattestman** [comment]
The changes have been successfully committed and pushed to your fork, and a pull request has been created! Here are the details:

### Pull Request
- **Title:** Add NPM dependencies documentation
- **Description:** This pull request adds a new file `NPM_DEPENDENCIES.md` documenting the list of NPM dependencies used in the project.
- **PR Link:** [View Pull Request](https://github.com/SomethingGeneric/website/pull/24)

You can review the changes and merge the pull request if everything looks good. If you have any further modifications or questions, feel free to ask!
